apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: fcj
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: minhkhoi24k/fcj-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5173
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: fcj
spec:
  selector:
    app: frontend
  ports:
    - port: 5173
      targetPort: 5173
