apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: fcj
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: minhkhoi24k/fcj-resbar-mysql:latest
          ports:
            - containerPort: 3306
          envFrom:
            - secretRef:
                name: mysql-secret
          volumeMounts:
            - name: mysql-pv
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-pv
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: fcj
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
